web/apps/about/urls.py
import django.urls
import django.views.generic

import apps.about.views


app_name = "about"
urlpatterns = [
    django.urls.path("", apps.about.views.Description.as_view(), name="main"),
]

web/apps/homepage/urls.py
from django.urls import path

from apps.homepage.views import Home, CalendarView, Games, Program, AdminProgram

app_name = "homepage"
urlpatterns = [
    path("", Home.as_view(), name="main"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("programs/", Games.as_view(), name="programs"),
    path("school_program/", Program.as_view(), name="school_program"),
    path("admin_program/", AdminProgram.as_view(), name="admin_program"),
]

web/apps/news/urls.py
from django.urls import path

from apps.news.views import NewsDetailView, Description


app_name = "news"
urlpatterns = [
    path("news/", Description.as_view(), name="main"),
    path('news/<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
]

web/apps/users/urls.py
from django.urls import path
from apps.users import views

app_name = "users"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path('delete_avatar/', views.delete_avatar, name='delete_avatar'),
]

web/apps/works/urls.py
from django.urls import path

from apps.works.views import DashboardView, EventListView, EventCreateView, \
    EventUpdateView, EventDeleteView, EventDetailView

app_name = "works"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("events/", EventListView.as_view(), name="events"),
    path("events/add/", EventCreateView.as_view(), name="event_add"),
    path("events/<int:pk>/edit/", EventUpdateView.as_view(),
         name="event_edit"),
    path(
        "events/<int:pk>/delete/", EventDeleteView.as_view(),
        name="event_delete",
    ),
    path('events/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
]

web/web/urls.py
from django.conf import settings
import django.conf.urls.static
import django.contrib
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("apps.homepage.urls")),
    path("news/", include("apps.news.urls")),
    path("api/", include("apps.api.urls")),
    path("foods/", include("apps.foods.urls")),
    path("problems/", include("apps.problems.urls")),
    path("classes/", include("apps.classes.urls")),
    path("works/", include("apps.works.urls")),
    path("about/", include("apps.about.urls")),
    path("stats/", include("apps.stats.urls")),
    path("auth/", include("apps.users.urls")),
    path("admin/", django.contrib.admin.site.urls),
]

urlpatterns += django.conf.urls.static.static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)
if settings.DEBUG:
    urlpatterns += django.conf.urls.static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

web/apps/users/models.py
import pathlib
import re
import sys
import uuid

import django.db.models
import django.contrib.auth.models
from django.conf import settings
import sorl.thumbnail


class LoginUserManager(django.contrib.auth.models.BaseUserManager):
    def normalize_email(self, email):
        email = super().normalize_email(email)
        email = email.lower()
        local_part, domain = email.split("@")

        local_part = local_part.split("+")[0]

        if domain in ["yandex.ru", "ya.ru"]:
            domain = "yandex.ru"
            local_part = local_part.replace(".", "-")
        elif domain == "gmail.com":
            local_part = local_part.replace(".", "")

        local_part = re.sub(r"\+.*", "", local_part)
        return f"{local_part}@{domain}"

    def get_queryset(self):
        return super().get_queryset().select_related("profile")

    def active(self):
        return self.get_queryset().filter(is_active=True)

    def by_mail(self, email):
        normalized_email = self.normalize_email(email)
        return self.get_queryset().filter(email=normalized_email).first()


class CustomUser(django.contrib.auth.models.AbstractUser):
    attempts_count = django.db.models.PositiveIntegerField(
        default=0,
    )

    def unlock_account(self):
        self.is_active = True
        self.attempts_count = 0
        self.save()

    class Meta:
        verbose_name = "кастомный пользователь"
        verbose_name_plural = "кастомные пользователи"

    def __str__(self):
        return self.username


class User(CustomUser):
    objects = LoginUserManager()

    def save(self, *args, **kwargs):
        self.email = User.objects.normalize_email(self.email)
        super().save(*args, **kwargs)

    class Meta:
        proxy = True

    def get_profile(self):
        return self.profile


if "makemigrations" not in sys.argv and "migrate" not in sys.argv:
    User._meta.get_field("email")._unique = True


class ProfileManager(django.db.models.Manager):
    def user_detail(self, pk):
        return (
            self.get_queryset()
            .filter(pk=pk)
            .values(
                "user__email",
                "user__first_name",
                "user__last_name",
                Profile.birthday.field.name,
                Profile.image.field.name,
                Profile.coffee_count.field.name,
            )
        )


class Profile(django.db.models.Model):
    def get_upload_file(self, filename):
        ext = filename.split(".")[-1]
        filename = f"{uuid.uuid4()}.{ext}"
        return pathlib.Path("users") / str(self.id) / filename

    objects = ProfileManager()

    user = django.db.models.OneToOneField(
        User,
        on_delete=django.db.models.CASCADE,
    )
    birthday = django.db.models.DateField(
        null=True,
        blank=True,
        help_text="Дата вашего рождения",
    )
    image = django.db.models.ImageField(
        verbose_name="изображение",
        upload_to=get_upload_file,
        blank=True,
        null=True,
        help_text="Аватарка",
    )

    class Meta:
        verbose_name = "дополнительное поле"
        verbose_name_plural = "дополнительные поля"
        ordering = ("user",)

    def __str__(self):
        return self.user.username

    def get_image_350x350(self):
        return sorl.thumbnail.get_thumbnail(
            self.image,
            "350x350",
            crop="center",
            quality=85,
        )

class RegistrationToken(django.db.models.Model):
    token = django.db.models.CharField(
        verbose_name="Токен регистрации",
        max_length=64,
        unique=True,
        default=uuid.uuid4,
    )
    is_active = django.db.models.BooleanField(
        verbose_name="Активен",
        default=True,
    )

    class Meta:
        verbose_name = "токен регистрации"
        verbose_name_plural = "токены регистрации"

    def __str__(self):
        return str(self.token)

web/apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from apps.users.models import User, Profile, RegistrationToken


class SignUpForm(UserCreationForm):
    registration_token = forms.CharField(
        label='Регистрационный токен',
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Токен',
            'autocomplete': 'email'
        }),
        help_text='Введите токен, полученный от администратора'
    )
    email = forms.EmailField(
        label="Email",
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'example@example.com',
            'autocomplete': 'email'
        }),
        help_text="Обязательное поле. Введите действующий email."
    )

    username = forms.CharField(
        label="Имя пользователя",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'username',
            'autocomplete': 'username'
        }),
        help_text="Только буквы, цифры и @/./+/-/_."
    )

    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Пароль',
            'autocomplete': 'new-password'
        }),
        help_text="""
            <ul class="password-requirements">
                <li>Минимум 8 символов</li>
                <li>Не должен быть похож на имя пользователя</li>
                <li>Не должен быть слишком простым</li>
            </ul>
        """
    )

    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Подтвердите пароль',
            'autocomplete': 'new-password'
        }),
        help_text="Введите тот же пароль, что и выше, для проверки."
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError(
                "Пользователь с таким email уже существует.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("Это имя пользователя уже занято.")
        return username

    def clean_registration_token(self):
        token_value = self.cleaned_data.get('registration_token')
        try:
            token = RegistrationToken.objects.get(token=token_value)
        except RegistrationToken.DoesNotExist:
            raise ValidationError('Неверный регистрационный токен')

        if not token or not token.is_active:
            raise ValidationError('Токен уже использован или истек')

        return token_value


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")
        labels = {
            'username': 'Имя пользователя',
            'email': 'Email',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password', None)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("birthday", "image")
        labels = {
            'birthday': 'Дата рождения',
            'image': 'Аватар',
        }
        widgets = {
            'birthday': forms.DateInput(
                attrs={
                    'type': 'date',
                    'class': 'form-control'
                },
                format='%Y-%m-%d'
            ),
        }

web/apps/users/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from apps.users.forms import SignUpForm, UserUpdateForm, ProfileUpdateForm
from apps.users.models import Profile, RegistrationToken


class RegisterView(View):
    template_name = "users/signup.html"

    def get(self, request):
        form = SignUpForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            token_value = form.cleaned_data['registration_token']
            token = RegistrationToken.objects.get(token=token_value)

            if not token:
                form.add_error('registration_token', 'Токен уже использован или истек')
                return render(request, self.template_name, {'form': form})

            user = form.save()
            Profile.objects.create(user=user)

            token.is_active = False
            token.save()
            login(request, user)
            return redirect('homepage:main')

        return render(request, self.template_name, {'form': form})


class UserLoginView(LoginView):
    template_name = "users/login.html"


def user_logout(request):
    logout(request)
    return redirect("users:login")


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        profile, created = Profile.objects.get_or_create(user=request.user)

        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=profile)

        return render(
            request,
            "users/profile.html",
            {
                "user_form": user_form,
                "profile_form": profile_form,
                "birthday_value": profile.birthday.strftime(
                    '%Y-%m-%d') if profile.birthday else ''
            },
        )

    def post(self, request):
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect("users:profile")

        return render(
            request,
            "users/profile.html",
            {
                "user_form": user_form,
                "profile_form": profile_form,
                "birthday_value": request.POST.get('birthday', '')
            },
        )


@require_POST
@login_required
def delete_avatar(request):
    profile = request.user.profile
    if profile.image:
        profile.image.delete()
        profile.image = None
        profile.save()
    return JsonResponse({'status': 'success'})

web/templates/includes/footer.html
<footer class="mt-auto py-4 px-3 bg-body bg-opacity-75 border-top shadow-sm backdrop-blur">
  <div class="container">
    <div class="row align-items-center justify-content-between">

      <div class="col-md-auto text-center text-md-start mb-2 mb-md-0">
        <span class="text-muted small">&copy; 2025 — Сделано с <i class="bi bi-heart-fill text-danger"></i> на Django</span>
      </div>

      <div class="col-md-auto text-center text-md-end">
        <a href="https://github.com/Lyceum-KFU" class="text-muted me-3" target="_blank"><i class="bi bi-github fs-5"></i></a>
        <a href="https://t.me/kfu_luceum" class="text-muted me-3" target="_blank"><i class="bi bi-telegram fs-5"></i></a>
        <a href="mailto:12447690@mail.ru" class="text-muted"><i class="bi bi-envelope fs-5"></i></a>
      </div>

    </div>
  </div>
</footer>

web/templates/includes/header.html
{% load static %}
{% load active_link_tags %}

<header class="py-3 px-3 sticky-top backdrop-blur bg-body bg-opacity-75 shadow-sm border-bottom">
  <div class="container d-flex flex-wrap justify-content-between align-items-center">
    <a href="/" class="d-flex align-items-center text-decoration-none dark:text-light">
      <img src="{% static 'img/logo.png' %}" alt="Logo" height="40" class="me-2">
      <span class="fs-4 fw-semibold">Умная школа</span>
    </a>

    <nav class="d-none d-md-flex gap-4 align-items-center">
      <a href="{% url 'homepage:main' %}" class="nav-link fw-medium {% if request.resolver_match.view_name == 'homepage:main' %}choose{% endif %}">Главная</a>
      <a href="{% url 'homepage:calendar' %}" class="nav-link fw-medium {% if request.resolver_match.view_name == 'homepage:calendar' %}choose{% endif %}">Календарь</a>
      <a href="{% url 'news:main' %}" class="nav-link fw-medium {% if request.resolver_match.view_name == 'news:main' %}choose{% endif %}">Новости</a>
      <a href="{% url 'about:main' %}" class="nav-link fw-medium {% if request.resolver_match.view_name == 'about:main' %}choose{% endif %}">О нас</a>
      <a href="{% url 'homepage:programs' %}" class="nav-link fw-medium {% if request.resolver_match.view_name == 'homepage:programs' %}choose{% endif %}">Программы</a>
    </nav>

    <div class="d-flex align-items-center gap-3">

      <div class="dropdown">
        <button class="btn border-0 dropdown-toggle d-flex align-items-center gap-1" id="themeDropdown" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-circle-half"></i> <span class="d-none d-sm-inline">Тема</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end shadow-sm rounded">
          <li><button class="dropdown-item" data-bs-theme-value="light"><i class="bi bi-sun me-2 text-warning"></i>Светлая</button></li>
          <li><button class="dropdown-item" data-bs-theme-value="dark"><i class="bi bi-moon me-2 text-primary"></i>Тёмная</button></li>
        </ul>
      </div>

      {% if request.resolver_match.view_name != 'users:login' %}
        {% if request.user.is_authenticated %}
          <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static 'img/default_user_avatar.jpg' %}{% endif %}" class="rounded-circle me-2" width="40" height="40" alt="{{ request.user.username }}">
              <span class="fw-medium">{{ request.user.username }}</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end shadow-sm rounded">
              <li><a class="dropdown-item" {% if view_name != 'users:profile' %}href="{% url 'users:profile' %}"{% endif %}>Мой профиль</a></li>
              <li><a class="dropdown-item" href="{% url 'works:dashboard' %}">Работа</a></li>
              {% if request.user.is_staff %}
                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
              {% endif %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item text-danger" href="{% url 'users:logout' %}">Выйти</a></li>
            </ul>
          </div>
        {% else %}
          <a href="{% url 'users:login' %}" class="btn btn-outline-primary fw-medium">Войти</a>
        {% endif %}
      {% else %}
      <a href="{% url 'users:login' %}" class="btn btn-outline-primary fw-medium" style="visibility: hidden;">Войти</a>
      {% endif %}
    </div>
  </div>
</header>

web/templates/includes/messages.html
{% if messages %}
  <div class="notification-container position-fixed top-0 end-0 p-3" style="z-index: 1100">
    {% for message in messages %}
      <div class="alert alert-{% if message.tags == 'error' %}warning{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show shadow-lg"
           role="alert"
           style="min-width: 300px; transition: all 0.5s ease">
        <div class="d-flex align-items-center">
          {% if message.tags == 'error' %}
            <i class="bi bi-exclamation-triangle-fill me-2"></i>
          {% elif message.tags == 'success' %}
            <i class="bi bi-check-circle-fill me-2"></i>
          {% elif message.tags == 'info' %}
            <i class="bi bi-info-circle-fill me-2"></i>
          {% elif message.tags == 'warning' %}
            <i class="bi bi-exclamation-circle-fill me-2"></i>
          {% endif %}

          <div class="flex-grow-1">
            {{ message }}
          </div>

          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    {% endfor %}
  </div>
{% endif %}

web/templates/includes/user_form.html
{% load static %}
{% load i18n %}

{% with request.resolver_match.view_name as view_name %}
  <form method="POST" class="form-user-auth mt-5" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="d-flex flex-column col-10 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-3 ms-auto me-auto">
      <h1 class="h3 mb-4 fw-bold text-center text-primary">{{ title }}</h1>

      <!-- Поля ввода -->
      <div class="form-group d-flex flex-column gap-3">
        {% for field in form %}
          {% if field.field.widget.input_type != "checkbox" %}
            <div class="form-floating">
              {{ field }}
              <label for="{{ field.id_for_label }}">
                {% if view_name == "users:login" and forloop.first %}
                  {{ field.field.widget.attrs.placeholder }}
                {% else %}
                  {{ field.label }}
                {% endif %}
              </label>
              {% if field.errors %}
                <div class="invalid-feedback">
                  {{ field.errors|first }}
                </div>
              {% endif %}
            </div>
          {% endif %}
        {% endfor %}
      </div>

      <!-- Чекбоксы -->
      {% for field in form %}
        {% if field.field.widget.input_type == "checkbox" %}
          <div class="form-check ms-auto me-auto mt-3">
            {{ field }}
            <label class="form-check-label" for="{{ field.id_for_label }}">
              {{ field.label }}
            </label>
          </div>
        {% endif %}
      {% endfor %}

      <!-- Общие ошибки формы -->
      {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger mt-2 text-center" role="alert">
            {{ error }}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <!-- Кнопка отправки и дополнительные ссылки -->
    <div class="d-flex flex-column text-center mt-4">
      <button class="btn btn-primary btn-lg w-100 py-2" type="submit">{{ submit_text }}</button>
      {% if view_name == "users:login" %}
        <div class="mt-4">
          <p class="mb-2">
            {% trans "dont_have_account_yet" %}
            <a href="{% url 'users:signup' %}" class="text-decoration-none text-primary fw-semibold">
              {% trans "create_it" %}
            </a>
          </p>
        </div>
      {% endif %}
    </div>

    <!-- Скрытые элементы -->
    <div class="d-none">
      <span id="serverTime">{{ server_time }}</span>
    </div>
  </form>
{% endwith %}